theme: jekyll-theme-hacker
title: SF6 Things
tagline: Documentar algumas coisas sobre personagens e conhecimentos gerais do jogo ao longo do ciclo de vida
description: Documentar algumas coisas sobre personagens e conhecimentos gerais do jogo ao longo do ciclo de vida
logo: /assets/SF6Logo.png
include:
 - Season 2
plugins:
  - jekyll-seo-tag